volumes:
  static:

services:
  backend:
    build: ./backend/
    #env_file: .env
    volumes:
      - static:/app/static
  gateway:
    build: ./gateway/
    #env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
